package com.mobilefork.hermesagent.ui.i18n

enum class PrivacyText(private val translations: List<String>) {
    REPORT(listOf("Report AI content", "举报 AI 内容", "Denunciar contenido de IA", "KI-Inhalt melden", "Denunciar conteúdo de IA", "Signaler un contenu IA")),
    PREVIEW(listOf("Review and edit the exact text to send", "查看并编辑要发送的确切文本", "Revisa y edita el texto exacto que se enviará", "Den zu sendenden Text prüfen und bearbeiten", "Revise e edite o texto exato a enviar", "Vérifiez et modifiez le texte exact à envoyer")),
    REPORT_NOTICE(listOf(
        "Only the text you preview, reason, optional notes, app version and edition are sent to the developer's private Cloudflare service when you tap Submit report. No other chats or attachments are sent. Remove personal data and secrets. Reports help improve safety; no response is promised. Active reports expire after 30 days (cleanup within one hour); provider backups have separate retention. A private deletion receipt is saved on this device. This is not an emergency service.",
        "只有在点击提交举报后，预览的文本、原因、可选备注、应用版本和发行版才会发送到开发者的私有 Cloudflare 服务。不会发送其他聊天或附件。请删除个人资料和密钥。举报用于改善安全性，不保证回复。有效举报在 30 天后过期（一小时内清理）；服务商备份另有保留期限。私有删除凭据保存在此设备上。这不是紧急服务。",
        "Solo al pulsar Enviar denuncia se envían el texto revisado, motivo, notas opcionales, versión y edición al servicio privado de Cloudflare del desarrollador. No se envían otros chats ni adjuntos. Elimina datos personales y secretos. Las denuncias mejoran la seguridad; no se garantiza respuesta. Caducan a los 30 días (limpieza en una hora); las copias del proveedor tienen otra retención. Se guarda un recibo privado de eliminación en este dispositivo. No es un servicio de emergencias.",
        "Erst beim Tippen auf Meldung senden werden der geprüfte Text, Grund, optionale Notizen, App-Version und Edition an den privaten Cloudflare-Dienst des Entwicklers gesendet. Keine anderen Chats oder Anhänge. Persönliche Daten und Geheimnisse entfernen. Meldungen dienen der Sicherheit; keine Antwortgarantie. Aktive Meldungen verfallen nach 30 Tagen (Bereinigung binnen einer Stunde); Anbieter-Backups haben eigene Fristen. Ein privater Löschbeleg bleibt auf diesem Gerät. Kein Notfalldienst.",
        "Somente ao tocar em Enviar denúncia, o texto revisado, motivo, notas opcionais, versão e edição são enviados ao serviço privado Cloudflare do desenvolvedor. Nenhum outro chat ou anexo é enviado. Remova dados pessoais e segredos. As denúncias ajudam a melhorar a segurança; não há resposta garantida. Expiram após 30 dias (limpeza em uma hora); backups do provedor têm retenção separada. Um recibo privado de exclusão fica neste dispositivo. Não é um serviço de emergência.",
        "Seuls le texte vérifié, le motif, les notes facultatives, la version et l’édition sont envoyés au service Cloudflare privé du développeur lorsque vous touchez Envoyer le signalement. Aucun autre chat ni pièce jointe. Retirez les données personnelles et secrets. Les signalements améliorent la sécurité ; aucune réponse n’est promise. Ils expirent après 30 jours (nettoyage sous une heure) ; les sauvegardes du fournisseur ont une durée distincte. Un reçu privé de suppression reste sur cet appareil. Ce n’est pas un service d’urgence."
    )),
    NOTES(listOf("Optional notes", "可选备注", "Notas opcionales", "Optionale Notizen", "Notas opcionais", "Notes facultatives")),
    SUBMIT(listOf("Submit report", "提交举报", "Enviar denuncia", "Meldung senden", "Enviar denúncia", "Envoyer le signalement")),
    CANCEL(listOf("Cancel", "取消", "Cancelar", "Abbrechen", "Cancelar", "Annuler")),
    CLOSE(listOf("Close", "关闭", "Cerrar", "Schließen", "Fechar", "Fermer")),
    DELETE(listOf("Delete report", "删除举报", "Eliminar denuncia", "Meldung löschen", "Excluir denúncia", "Supprimer le signalement")),
    SENT(listOf("Report received by the developer's service.", "开发者服务已收到举报。", "El servicio del desarrollador recibió la denuncia.", "Der Entwicklerdienst hat die Meldung erhalten.", "O serviço do desenvolvedor recebeu a denúncia.", "Le service du développeur a reçu le signalement.")),
    FAILED(listOf("Delivery not confirmed. You can retry this exact report, or delete its receipt from Privacy and safety to remove any uncertain delivery.", "未确认送达。可重试同一举报，或在隐私与安全中删除其凭据以清除可能已送达的举报。", "Entrega no confirmada. Reintenta esta misma denuncia o elimínala desde Privacidad y seguridad para retirar una entrega incierta.", "Zustellung nicht bestätigt. Dieselbe Meldung erneut senden oder unter Datenschutz und Sicherheit löschen, um eine ungewisse Zustellung zu entfernen.", "Entrega não confirmada. Tente novamente a mesma denúncia ou exclua-a em Privacidade e segurança para remover uma entrega incerta.", "Envoi non confirmé. Réessayez ce même signalement ou supprimez-le dans Confidentialité et sécurité pour retirer un envoi incertain.")),
    DELETED(listOf("The active report is deleted or already absent.", "有效举报已删除或已不存在。", "La denuncia activa se eliminó o ya no existe.", "Die aktive Meldung wurde gelöscht oder ist bereits nicht vorhanden.", "A denúncia ativa foi excluída ou já não existe.", "Le signalement actif est supprimé ou déjà absent.")),
    DELETE_FAILED(listOf("Deletion not confirmed. Your receipt was kept; retry when online.", "未确认删除。凭据已保留，请联网后重试。", "Eliminación no confirmada. Se conservó el recibo; reintenta con conexión.", "Löschung nicht bestätigt. Beleg bleibt gespeichert; online erneut versuchen.", "Exclusão não confirmada. Recibo mantido; tente novamente on-line.", "Suppression non confirmée. Le reçu est conservé ; réessayez en ligne.")),
    PRIVACY(listOf("Privacy and safety", "隐私与安全", "Privacidad y seguridad", "Datenschutz und Sicherheit", "Privacidade e segurança", "Confidentialité et sécurité")),
    RECEIPTS(listOf("Report deletion receipts", "举报删除凭据", "Recibos para eliminar denuncias", "Löschbelege für Meldungen", "Recibos de exclusão de denúncias", "Reçus de suppression des signalements")),
    NO_REPORTS(listOf("No report receipts on this device.", "此设备上没有举报凭据。", "No hay recibos en este dispositivo.", "Keine Meldebelege auf diesem Gerät.", "Nenhum recibo neste dispositivo.", "Aucun reçu sur cet appareil.")),
    CHILD(listOf("Child safety", "儿童安全", "Seguridad infantil", "Kinderschutz", "Segurança infantil", "Sécurité des enfants")),
    VIOLENCE(listOf("Violence", "暴力", "Violencia", "Gewalt", "Violência", "Violence")),
    SEXUAL(listOf("Sexual content", "色情内容", "Contenido sexual", "Sexuelle Inhalte", "Conteúdo sexual", "Contenu sexuel")),
    HATE(listOf("Hate", "仇恨", "Odio", "Hass", "Ódio", "Haine")),
    DECEPTION(listOf("Deceptive content", "欺骗性内容", "Contenido engañoso", "Täuschende Inhalte", "Conteúdo enganoso", "Contenu trompeur")),
    OTHER(listOf("Other concern", "其他问题", "Otro problema", "Anderes Problem", "Outro problema", "Autre problème")),
    REMOTE_REVOKED(listOf("Remote processing consent revoked.", "已撤销远程处理同意。", "Consentimiento remoto revocado.", "Zustimmung zur Fernverarbeitung widerrufen.", "Consentimento remoto revogado.", "Consentement distant révoqué.")),
    REVOKED_RESTART(listOf("Consent revoked, but active work did not stop cleanly. Force stop the app in Android Settings to finish cleanup.", "已撤销同意，但活动任务未完全停止。请在 Android 设置中强行停止应用以完成清理。", "Consentimiento revocado, pero el trabajo activo no se detuvo correctamente. Fuerza la detención de la app en Android para completar la limpieza.", "Zustimmung widerrufen, laufende Arbeit aber nicht sauber beendet. App in Android zwangsweise beenden, um die Bereinigung abzuschließen.", "Consentimento revogado, mas o trabalho ativo não parou corretamente. Force a parada do app no Android para concluir a limpeza.", "Consentement révoqué, mais le travail actif ne s’est pas arrêté correctement. Forcez l’arrêt de l’app dans Android pour terminer le nettoyage.")),
    SAVE_FAILED(listOf("Could not save this privacy choice. Please retry; no new consent was recorded.", "无法保存隐私选择。请重试，尚未记录新的同意。", "No se pudo guardar esta elección. Reintenta; no se registró nuevo consentimiento.", "Datenschutzentscheidung nicht gespeichert. Erneut versuchen; keine neue Zustimmung erfasst.", "Não foi possível salvar a escolha. Tente novamente; nenhum novo consentimento foi registrado.", "Impossible d’enregistrer ce choix. Réessayez ; aucun nouveau consentement enregistré.")),
    POLICY_OPEN_FAILED(listOf("No browser could open the policy. The address is shown below.", "没有浏览器可以打开政策。地址如下。", "Ningún navegador pudo abrir la política. La dirección aparece abajo.", "Kein Browser konnte die Erklärung öffnen. Die Adresse steht unten.", "Nenhum navegador abriu a política. O endereço aparece abaixo.", "Aucun navigateur n’a ouvert la politique. L’adresse figure ci-dessous."));

    fun inLanguage(language: AppLanguage): String = translations[language.ordinal]
}

fun HermesStrings.privacyText(text: PrivacyText): String = text.inLanguage(language)
