package com.mobilefork.hermesagent.ui.chat

import com.mobilefork.hermesagent.R

data class SignalIntelligenceQuickAction(
    val id: String,
    val label: String,
    val diagnosticAction: String,
    val prompt: String,
    val iconRes: Int,
)

val SIGNAL_INTELLIGENCE_QUICK_ACTIONS = listOf(
    SignalIntelligenceQuickAction(
        id = "signal_overview",
        label = "Signal Overview",
        diagnosticAction = "signal_awareness_report",
        prompt = "Run android_device_diagnostics_tool action=signal_awareness_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_evidence",
        label = "Evidence Bundle",
        diagnosticAction = "agent_signal_evidence_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_evidence_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "agent_environment",
        label = "Agent Environment",
        diagnosticAction = "agent_environment_report",
        prompt = "Run android_device_diagnostics_tool action=agent_environment_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "agent_observation",
        label = "Agent Observation",
        diagnosticAction = "agent_observation_report",
        prompt = "Run android_device_diagnostics_tool action=agent_observation_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "card_manifest",
        label = "Card Manifest",
        diagnosticAction = "agent_card_manifest_report",
        prompt = "Run android_device_diagnostics_tool action=agent_card_manifest_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "soc_compatibility",
        label = "SOC Compatibility",
        diagnosticAction = "soc_compatibility_report",
        prompt = "Run android_device_diagnostics_tool action=soc_compatibility_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "backend_risk",
        label = "Backend Risk",
        diagnosticAction = "gpu_backend_risk_report",
        prompt = "Run android_device_diagnostics_tool action=gpu_backend_risk_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "inference_compatibility",
        label = "Inference Fit",
        diagnosticAction = "local_inference_compatibility_report",
        prompt = "Run android_device_diagnostics_tool action=local_inference_compatibility_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "runtime_backend",
        label = "Runtime Backend",
        diagnosticAction = "local_backend_runtime_report",
        prompt = "Run android_device_diagnostics_tool action=local_backend_runtime_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "runtime_stability",
        label = "Runtime Stability",
        diagnosticAction = "device_performance_report",
        prompt = "Run android_device_diagnostics_tool action=device_performance_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_analyzer",
        label = "Wi-Fi Analyzer",
        diagnosticAction = "wifi_analyzer_report",
        prompt = "Run android_device_diagnostics_tool action=wifi_analyzer_report refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_nearby",
        label = "Nearby Wi-Fi",
        diagnosticAction = "wifi_scan",
        prompt = "Run android_device_diagnostics_tool action=wifi_scan refresh=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_occupancy",
        label = "Wi-Fi Occupancy",
        diagnosticAction = "wifi_channel_utilization",
        prompt = "Run android_device_diagnostics_tool action=wifi_channel_utilization refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_analyzer",
        label = "Bluetooth Analyzer",
        diagnosticAction = "bluetooth_analyzer_report",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_analyzer_report refresh=false",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_history",
        label = "Bluetooth Trends",
        diagnosticAction = "bluetooth_signal_history",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_signal_history refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "sensor_analyzer",
        label = "Sensor Analyzer",
        diagnosticAction = "sensor_analyzer_report",
        prompt = "Run android_device_diagnostics_tool action=sensor_analyzer_report include_snapshot=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "motion_history",
        label = "Motion Trends",
        diagnosticAction = "motion_sensor_history",
        prompt = "Run android_device_diagnostics_tool action=motion_sensor_history sample=true sensor_types=accelerometer,gyroscope,linear_acceleration,rotation_vector",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "radio_limits",
        label = "Radio Signals",
        diagnosticAction = "radio_signal_graph",
        prompt = "Run android_device_diagnostics_tool action=radio_signal_graph",
        iconRes = R.drawable.ic_action_cog,
    ),
)
